config/routes.rb
Rails.application.routes.draw do
  resources :courses
  resources :schools
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'schools#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
end

app/models/school.rb
class School < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: [:show, :edit, :update, :destroy]

  def index
    @courses = Course.all
  end

  def show
  end

  def new
    @course = Course.new
  end

  def edit
  end

  def create
    @course = Course.new(course_params)

    respond_to do |format|
      if @course.save
        flash[:success] = 'Curso criado com sucesso.'
        format.html { redirect_to @course }
        format.json { render :show, status: :created, location: @course }
      else
        flash[:danger] = 'Erro ao criar curso'
        format.html { render :new }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @course.update(course_params)
        flash[:success] = 'Curso atualizado com sucesso.'
        format.html { redirect_to @course}
        format.json { render :show, status: :ok, location: @course }
      else
        flash[:success] = 'Erro au atualizar curso.'
        format.html { render :edit }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @course.destroy
    respond_to do |format|
      flash[:success] = 'Curso deletado com sucesso.'
      format.html { redirect_to courses_url }
      format.json { head :no_content }
    end
  end

  private
    def set_course
      @course = Course.find(params[:id])
    end

    def course_params
      params.require(:course).permit(:title, :description, :content, :duration, :price)
    end
end

app/controllers/schools_controller.rb
class SchoolsController < ApplicationController
  before_action :set_school, only: [:show, :edit, :update, :destroy]

  def index
    @schools = School.all
  end

  def show
  end

  def new
    @school = School.new
  end

  def edit
  end

  def create
    @school = School.new(school_params)

    respond_to do |format|
      if @school.save
        flash[:success] = 'Escola criada com sucesso.'
        format.html { redirect_to @school }
        format.json { render :show, status: :created, location: @school }
      else
        flash[:danger] = 'Erro ai criar escola'
        format.html { render :new }
        format.json { render json: @school.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @school.update(school_params)
        flash[:success] = 'Escola atualizada com sucesso'
        format.html { redirect_to @school }
        format.json { render :show, status: :ok, location: @school }
      else
        flash[:danger] = 'Ocorreram erros ao atualizar a escola'
        format.html { render :edit }
        format.json { render json: @school.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @school.destroy
    respond_to do |format|
      flash[:success] = 'Escola deletado com sucesso'
      format.html { redirect_to schools_url }
      format.json { head :no_content }
    end
  end

  private

    def set_school
      @school = School.find(params[:id])
    end

    def school_params
      params.require(:school).permit(:name, :email, :pitch, :subdomain)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/views/courses/_form.html.erb
<%= form_for(@course, html: {class: 'form col-sm-8'} ) do |f| %>

  <div class="field form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>

  <div class="field form-group">
    <%= f.label :description %>
    <%= f.text_field :description, class: 'form-control' %>
  </div>

  <div class="field form-group">
    <%= f.label :content %>
    <%= f.text_field :content, class: 'form-control' %>
  </div>

  <div class="field form-group">
    <%= f.label :duration %>
    <%= f.number_field :duration, class: 'form-control' %>
  </div>

  <div class="field form-group">
    <%= f.label :price %>
    <%= f.text_field :price, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= f.submit class: 'btn btn-success' %>
    <%= link_to 'Voltar', courses_path, class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/courses/edit.html.erb
<h1>Editar Curso</h1>

<%= render 'form', course: @course %>

app/views/courses/index.html.erb
<h1>Cursos</h1>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Content</th>
      <th>Duration</th>
      <th>Price</th>
      <th colspan="3">ações</th>
    </tr>
  </thead>

  <tbody>
    <% @courses.each do |course| %>
      <tr>
        <td><%= course.title %></td>
        <td><%= course.description %></td>
        <td><%= course.content %></td>
        <td><%= course.duration %></td>
        <td><%= course.price %></td>
        <td><%= link_to 'Mostrar', course, class: 'btn btn-primary btn-xs' %></td>
        <td><%= link_to 'Editar', edit_course_path(course), class: 'btn btn-info btn-xs' %></td>
        <td><%= link_to 'Deletar', course, method: :delete, data: { confirm: 'Você tem certeza?' }, class: 'btn btn-danger btn-xs' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to new_course_path, class: 'btn btn-primary' do %>
<i class="glyphicon glyphicon-plus"></i> Novo Curso
<% end %>

app/views/courses/new.html.erb
<h1>Novo Curso</h1>

<%= render 'form', course: @course %>

app/views/courses/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @course.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @course.description %>
</p>

<p>
  <strong>Content:</strong>
  <%= @course.content %>
</p>

<p>
  <strong>Duration:</strong>
  <%= @course.duration %>
</p>

<p>
  <strong>Price:</strong>
  <%= @course.price %>
</p>

<div>
<%= link_to 'Editar', edit_course_path(@course), class: 'btn btn-success' %>
<%= link_to 'Voltar', courses_path, class: 'btn btn-primary' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Escola</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div id="main-container" class="container">
      <div class="row">
        <div class="col-xs-3">
          <h3>Edools Project</h3>
        </div>
        <div class="col-xs-9">
          <div class="row">
          <% flash.each do |name, msg| -%>
            <%= content_tag :div, msg, class: "alert alert-#{name}" %>
          <% end -%>
          </div>
          <div class="row" style="margin-top: 3%">
            <%= yield %>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/schools/_form.html.erb
<%= form_for(@school,  html: {class: 'form col-sm-8'}) do |f| %>

  <div class="field form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>

  <div class="field form-group">
    <%= f.label :email %>
    <%= f.text_field :email, class: 'form-control' %>
  </div>

  <div class="field form-group">
    <%= f.label :pitch %>
    <%= f.text_field :pitch, class: 'form-control' %>
  </div>

  <div class="field form-group">
    <%= f.label :subdomain %>
    <%= f.text_field :subdomain, class: 'form-control' %>
  </div>

  <div class="actions form-group">
    <%= f.submit class: 'btn btn-success inline' %>

    <%= link_to 'Voltar', schools_path, class: 'btn btn-primary inline' %>
  </div>
<% end %>

app/views/schools/edit.html.erb
<h1>Editar Escola</h1>

<%= render 'form', school: @school %>

app/views/schools/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Lista de Escolas</h1>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Pitch</th>
      <th>Subdomain</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @schools.each do |school| %>
      <tr>
        <td><%= school.name %></td>
        <td><%= school.email %></td>
        <td><%= school.pitch %></td>
        <td><%= school.subdomain %></td>
        <td><%= link_to 'Mostrar', school, class: 'btn btn-primary btn-xs' %></td>
        <td><%= link_to 'Editar', edit_school_path(school), class: 'btn btn-info btn-xs' %></td>
        <td><%= link_to 'Deletar', school, method: :delete, data: { confirm: 'Você tem certeza ?' }, class: 'btn btn-danger btn-xs' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to new_school_path, class: 'btn btn-primary' do %>
<i class="glyphicon glyphicon-plus"></i> Nova Escola
<% end %>

app/views/schools/new.html.erb
<h1>Nova Escola</h1>

<%= render 'form', school: @school %>

app/views/schools/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @school.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @school.email %>
</p>

<p>
  <strong>Pitch:</strong>
  <%= @school.pitch %>
</p>

<p>
  <strong>Subdomain:</strong>
  <%= @school.subdomain %>
</p>

<div class="form-group">
<%= link_to 'Editar', edit_school_path(@school), class: 'btn-success' %> |
<%= link_to 'Voltar', schools_path, class: 'btn-primary' %>
</div>